version: '3'
services: 
  cypress-tests:
    image: 'dhis2/cypress-tests:master'
    shm_size: '2gb' 
    environment:
      CYPRESS_BASE_URL: ${CYPRESS_BASE_URL}
      CYPRESS_REPORT_PORTAL_ENABLED: ${CYPRESS_REPORT_PORTAL_ENABLED}
      CYPRESS_LOGIN_USERNAME: 'admin'
      CYPRESS_LOGIN_PASSWORD: 'district'
      CI_BUILD_ID: ${CI_BUILD_ID:-"test0002"}
      RP_TOKEN: ${RP_TOKEN}
    volumes: 
      - ./allure-results:/usr/test/allure-results
      - ./allure-report:/usr/test/allure-report
      - ./screenshots:/usr/test/cypress/screenshots
    entrypoint: "npm run cy:parallel"
